### ISSUE TITLE
Plugin doesn't work on Android 14

### ISSUE THREAD

**Issue by AllanThisgaard** [termux/termux-tasker#106]
**Problem description**
The plugin cannot be used inside Tasker, it throws the following error (see screenshot) when the action is selected: 

"Error: plugin error: missing, disabled,
not exported or no permission
receiver, or too many receivers." 

Attempting to grant permissions via a (root) Termux shell, also fails (see screenshot):

"Exception occurred while executing 'grant':
java.lang.IllegalArgumentException: Unknown permission: com.termux.permission.RUN_COMMAND" 

**Steps to reproduce**
1. Install latest Termux, Tasker and Termux:Tasker, on a device running Android 14. 
2. Attempt to use the plugin inside Tasker.

**Expected behavior**
The action is added to the task in Tasker. 

**Additional information**

* Termux application version: 
* Android OS version: 14, security updates till 5th of March 2024
* Device model: OnePlus 12 (EU), rooted, stock ROM 
I found this Reddit thread with the same issue as me, though the manual granting of permissions solved the problem there - it doesn't for me however: https://www.reddit.com/r/tasker/comments/13duyq1/error_with_termux_plugin/

Screenshots are here in OneDrive: https://1drv.ms/f/s!Ah5WmeA9l3h6l9JuD8_uq3g7UGk7nQ

It seems Termux:Tasker, in its current from, doesn't work with Android 14?

**Comment by AllanThisgaard** [comment]
This solved the problem.
Installing Termux from F-Droid, resulted in Tasker having the "Run command in Termux environment" permission available, so I could grant it via Android Settings. 

![Screenshot_2024-06-26-11-45-44-25_b783bf344239542886fee7b48fa4b892](https://github.com/termux/termux-tasker/assets/35352217/1fd52fb7-5fe4-485c-9803-3ee251d64792)

Suggestion: Have Termux warn the user upon start, if the Termux:Tasker application is installed, but the Termux application is not the version from F-Droid? Or show a more useful error in Tasker (if that's in your control?), when the action is selected, without the proper Termux version installed, or permissions granted. 

Would any of that be possible?

**Comment by agnostic-apollo** [comment]
Termux core team does not have any control over playstore releases, check https://github.com/termux/termux-app/discussions/4000. Playstore releases have removed the `RUN_COMMAND` permission defined by Termux app with a [different `TERMUX_INTERNAL` permission](https://github.com/termux-play-store/termux-apps/blob/3e6398dca6a712d218bbd6b681913bf99ccd5d34/termux-app/src/main/AndroidManifest.xml#L19), that's why you got `IllegalArgumentException: Unknown permission` when trying to grant it to tasker. Additionally, Tasker has not declared using the `TERMUX_INTERNAL` permission in its own app, so it can never be granted to it anyways, it only declares the `RUN_COMMAND` permission.

> Have Termux warn the user upon start, if the Termux:Tasker application is installed, but the Termux application is not the version from F-Droid?

That is not even allowed by default in Android, installation should fail, you have disabled signature checking somehow (which is a security risk), as per signing info in your screenshot, your Termux app is from playstore and Termux:Tasker from F-Droid. If you do manage to install Playstore release of Termux:Tasker, like from apkmirror, it may have worked as its still on `0.4` and does not use `RUN_COMMAND` permission but is not safe to use, check https://termux.dev/en/posts/general/2022/02/15/termux-apps-vulnerability-disclosures.html#termuxtasker-privilege-escalation-vulnerability.

https://github.com/termux/termux-app#installation
