### ISSUE TITLE
Scripts launched from Macrodroid

### ISSUE THREAD

**Issue by Primokorn** [termux/termux-tasker#13]
Hi,  
I'm a new user of Termux (and Termux Tasker) and I'd like to copy files from /sdcard to /data/user/0/ using [Macrodroid](https://play.google.com/store/apps/details?id=com.arlosoft.macrodroid).  

Macrodroid tells me that I need to create this directory:
> No ~/.termux/tasker/ directory
> You need to create a ~/.termux/tasker/ directory containing scripts to be executed.

AFAIK `/home` of Termux is `/data/data/com.termux/files/home/` so I tried to create it using `mkdir ~/.termux/tasker`. [Result](https://framapic.org/M5p04mdBvMnj/CrHwrpAvSxGG.png)  
So I've created it [manually](https://framapic.org/2f5BSnMzhckZ/61N9Ku6gObkd.png).  

I still have this same message on Macrodroid.  
I installed Termux app and this one (installed from F-Droid). I own a OnePlus 3T running an Oreo 8.1 AOSP based ROM.  

Thank you for your help.  

PS: the script I created is very and I think it should work:  
`#!/data/data/com.termux/files/usr/bin/sh` 
`cp /sdcard/Download/test.xml /data/data/user/0/...../test.xml`

**Comment by Neo-Oli** [comment]
You need to delete the `~/.termux/tasker` directory with the same app you created it (some kind of file explorer?) beceause these directories are now owned by the root user. Then you can create them in Termux with `mkdir -p ~/.termux/tasker`. Note the `-p` which creates the directories recursively. Your first error is beacues you tried to create the `tasker` directory in a directory that didn't exist.

**Comment by Neo-Oli** [comment]
Also your script won't work because `/data/user/0` is only available to root. If you're rooted you can run `su -c 'cp /sdcard/Download/test.xml /data/user/0/...../test.xml'`

**Comment by Neo-Oli** [comment]
@Primokorn If you need `su` for creating these folders something is very wrong and it will not work for the same reason as it won't work when you did it with the root explorer. Do you have any important data in termux? Otherwise I'd suggest simply reinstalling to fix these permission issues.

You need to avoid creating files in Termux (under `/data/data/com.termux/files` as root user at all cost, as Termux will then be unable to interact with them much. 

Also your command is wrong. It's `mkdir -p ~/.termux/tasker`

**Comment by Primokorn** [comment]
I reinstalled Termux and it works well now. Thanks again!
I made a typo for `mkdir` command.
