### ISSUE TITLE
Run scripts in sdcard

### ISSUE THREAD

**Issue by atbest** [termux/termux-tasker#14]
Could you please add support to run scripts in sdcard? It is much easier to edit and backup scripts in sdcard. Thanks!

**Comment by xeffyr** [comment]
> Could you please add support to run scripts in sdcard?

@atbest This support (for scripts) is already available:

1. For bash scripts:
```
bash /sdcard/myscript.sh
```

2. For python scripts:
```
python /sdcard/python_script.py
```
And more in such way...

If you are about executing programs (binary files) on sdcard - this can't be added due to file system limitation.

**Comment by fagcinsk** [comment]
https://forum.xda-developers.com/showthread.php?t=2743108

**Comment by agnostic-apollo** [comment]
You cannot directly execute scripts in external sd cards since those partitions are ideally mounted by default with the [noexec(https://superuser.com/questions/728127/what-does-noexec-flag-mean-when-mounting-directories-on-rhel) flag in android. Basically, files can't be granted execute permissions.

Even though you can bypass that restriction by passing the script path to its shell, its still a security risk to allow scripts that are stored in public directories that other apps can access to be executed in `termux` context and ideally shouldn't be allowed.

Editing scripts in `~/.termux/tasker` directory is not that difficult considering `termux` provides a `SAF` provider. Check [https://github.com/termux/termux-tasker#creating-and-modifying-scripts](https://github.com/termux/termux-tasker#creating-and-modifying-scripts) for more details.

However, you can use version [0.5](https://github.com/termux/termux-tasker/releases/tag/v0.5) along with [tudo](https://github.com/agnostic-apollo/tudo) or [sudo](https://github.com/agnostic-apollo/sudo) scripts to do store scripts directly in your plugin host app like Tasker if that is easier. The version `0.5` is required because argument parsing was broken in previous versions, now you can send your arbitrary script text surrounded with single quotes, after escaping any single quotes of course. Check the updated [README](https://github.com/termux/termux-tasker) for more information.
