### ISSUE TITLE
Inline script support? 

### ISSUE THREAD

**Issue by YumiSuki** [termux/termux-tasker#34]
I have just used termux-tasker plugin recently and I could not find options where I can set termux to execute script inline. There is only option to create file on sdcard and set path to the plugin. Most of the time, I want everything is inside tasker so it's much easier to back up and manage. If there are multiple tasks, I may need to create multiple file for termux which is hard to manage when time passed. If we could execute script inline and output is return to specific variable name it would be great.

**Comment by agnostic-apollo** [comment]
You can use version [0.5](https://github.com/termux/termux-tasker/releases/tag/v0.5) along with [tudo](https://github.com/agnostic-apollo/tudo) or [sudo](https://github.com/agnostic-apollo/sudo) scripts to do what you want. The version `0.5` is required because argument parsing was broken in previous versions, now you can send your arbitrary script text surrounded with single quotes, after escaping any single quotes of course. Check the updated [README](https://github.com/termux/termux-tasker) for more information.
