### ISSUE TITLE
Task executes asynchronously if runInTerminal == true

### ISSUE THREAD

**Issue by xalexalex** [termux/termux-tasker#39]
For tasks where runInTerminal == false, Tasker waits for the task to end (or for the timeout to elapse) before going on to the next action. This is also what I expected with runInTerminal == true, but what happens instead is that the task continues immediately. See [attached video](https://user-images.githubusercontent.com/16612842/106670576-8466a880-65ad-11eb-84bc-4afe96494853.mp4) where `Flash "Outside"` happens as soon as the terminal is launched.

Not sure whether this is a bug report or feature request. If this behavior is unintended, then it's a bug report. I think, however, that the most user-friendly (and least surprising) thing to do, would be to add an option to wait (or not) for the termux task to finish before running the next action, regardless of `runInTerminal`.

Also pinging #16 which is related.

**Comment by agnostic-apollo** [comment]
This is expected behaviour currently as mentioned in [README](https://github.com/termux/termux-tasker/tree/v0.5#plugin-configuration)

>Execute in a terminal session toggle defines whether the commands will be run in the background or in a foreground terminal session.

>If the toggle is enabled, a new terminal session will open up automatically in the foreground and commands will be run inside it. Result of commands is not returned to the plugin host app.

For [BackgroundJobs](https://github.com/termux/termux-app/blob/v0.106/app/src/main/java/com/termux/app/BackgroundJob.java#L52), the `stdout` and `stderr` is captured in variables and can easily be returned to the plugin host app, but for foreground terminal session commands, those are sent to the terminal view.

However, exit code is still available when terminal sessions [close](https://github.com/termux/termux-app/blob/v0.106/app/src/main/java/com/termux/app/TermuxActivity.java#L391), which can likely be sent back to the plugin host app, would require some work of course in `termux-app`, specially with linking sessions with their respective execution intents. And an addition of a `Wait for commands to end` toggle if `Execute in a terminal session` toggle is enabled in `termux-tasker`.

It might also be possible to capture `stdout` and `stderr` in variables and also sent them to the terminal view, but would require looking into.

**Comment by xalexalex** [comment]
Okay, got it.
So definitely not a bug, but a feature request. Perhaps one thing we could do is be a bit more clear regarding the fact that the foreground terminal session runs independently from the tasker task, which continues immediately. I'd read the documentation but it is not explicit, and perhaps even a bit misleading ("run in background" stops the tasker task, whereas "run in foreground" runs asynchronously while the task continues).
Do you prefer to keep the issue open as a feature request? Otherwise I'll close it.
Thanks!

**Comment by agnostic-apollo** [comment]
I agree, should make it more clear.

Leave it open, me or someone else would get to it. The `termux-app` `android-10` branch may also require merging with `master`, so big changes in `master` before that would cause problems.

**Comment by agnostic-apollo** [comment]
Closed by fecba503
