### ISSUE TITLE
No directory of ~/.termux/tasker

### ISSUE THREAD

**Issue by shingz96** [termux/termux-tasker#4]
when go to `tasker>plugin>configuration`
it show message of `No directory ~/.termux/tasker`
I have try to add in various place still the same
PS: the app i download from **F-droid** for testing purpose, is it that only the **play store** version will work?

**Comment by ElectroXexual** [comment]
You must create "~/.termux/tasker" folder and copy your scripts there before using tasker to execute them. Type "mkdir ~/.termux/tasker" in termux to create the directory and then "cp /sdcard/your/script.sh ~/.termux/tasker/" to copy your script to that folder. Then goto tasker>plugin>configuration and you will see your scripts there.

**Comment by shingz96** [comment]
but i cannot open the termux in launcher , i try to download the original [termux](https://play.google.com/store/apps/details?id=com.termux) in play store, seem Termux:Tasker or the original version can be installed either on of it only

**Comment by ElectroXexual** [comment]
Have you tried uninstaling and reinstalling termux and it's plugins from f-droid? or all from playstore?

**Comment by fornwall** [comment]
@shingz96 You need to install Termux and it's plugin from the same source - either Google Play or F-Droid. It doesn't work with mixing sources due to permissions issues (the signature needs to be the same).

**Comment by yassinose00** [comment]
for the people who didn't know what does the path "~/.termux/tasker" mean because of this weird ~ symbol that made no sense to me personally, this symbol means the home directory the termux starts at by default, so to create this directory you have to execute "cd ~" in the termux shell ofc to make sure that you're in the right place, and then you should create the .termux directory using the command "mkdir .termux" and then cd into it by typing "cd .termux" and then run "mkdir tasker" to create the tasker folder and "cd tasker" to go into it and then you can put your scripts there, I used nano which is a basic shell text editor that did get the job done of creating a simple script to test if everything is working properly

**Comment by xeffyr** [comment]
> so to create this directory you have to execute "cd ~" in the termux shell ofc to make sure that you're in the right place, and then you should create the .termux directory using the command "mkdir .termux" and then cd into it by typing "cd .termux" and then run "mkdir tasker"

Very long! Can be done by just `mkdir -p ~/.termux/tasker`.
