### ISSUE TITLE
Can't execute tasks if tasks are within a mount

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-tasker#45]
This is a bit of a weird one, and very specific to a certain kind of setup, so I would understand if this is a wontfix.

**Problem description**
If your `~/.termux/tasker` folder is inside a mount, Termux:Tasker only executes the files that exist in the unmounted state as well.

**Steps to reproduce**

### Setup test scripts 1 2 3

1. Setup script 1 and 2 inside `~/.termux/tasker` normally.
  * script1 prints `1 normal` to log
  * script2 prints `2 normal` to log

2. Mount a new folder to  `~/.termux`
3. Create another 2 scripts
  *  script2 prints `2 mounted` to log
    * has the same name as one of the normal scripts
  * script 3 print `3 mounted` to log
4. Run all 3 script with Tasker

#### Step by step:
```
$ mkdir -p ~/.termux/tasker 
$ echo "echo 1 normal > ~/log" >> ~/.termux/tasker/script1
$ echo "echo 2 normal > ~/log" >> ~/.termux/tasker/script2
$ chmod +x ~/.termux/tasker/*
$ mkdir ~/test
$ sudo mount --bind ~/test ~/.termux
$ mkdir -p ~/.termux/tasker
$ echo "echo 2 mounted > ~/log" >> ~/.termux/tasker/script2
$ echo "echo 3 mounted > ~/log" >> ~/.termux/tasker/script3
$ chmod +x ~/.termux/tasker/*
```

Create a test task running script 1 2 and 3

![Screenshot_20210512-023647_Tasker_small](https://user-images.githubusercontent.com/7983745/117901733-483d9500-b2cc-11eb-89bc-297f001dd220.png)

Enable `Continue Task After Error` for all of them.

Run this task.

Check the `~/log` file. It shows:
```
$ cat ~/log
2 mounted
$
```
**Expected behavior**
Since at the time of the execution only script2 and script3 are in `~/.termux/tasker`, these two should run and produce this logfile:
```
$ cat ~/log
2 mounted
3 mounted
$
```
But the only script that is able to run correctly is script2 since it exists in both the mounted and normal state. It does execute the mounted version (otherwise the log would show `2 normal`). 

**Additional information**
### Workaround
Things work as expected when you create empty executable files in the normal (not mounted) folder that have the same name as the scripts you wan to run (that's why script2 worked).

### Speculation

Termux:Tasker doesn't seem to be aware of the mount at all. The completion will show script1 and script2 (instead of script2 and script3).  When executing it seems to check if the files are executable within Termux:Tasker before running it via Termux. Probably here: https://github.com/termux/termux-tasker/blob/552d592e841595e7d0a531dd1235c04948a42a57/app/src/main/java/com/termux/tasker/utils/FileUtils.java#L144-L158
It will fail in a weird way for script1 (this task takes noticeably longer), which Termux:Tasker thinks is executable but actually is not. Script2 works as expected, because script2 is executable in the unmounted folder so Termux:Tasker lets it execute, which then executes script2 in the mounted folder. Termux:Tasker just refuses to execute script3 because it isn't in the unmounted folder, even though it would work.
I think it's a really interesting bug. I have no idea how to best solve it. Maybe have a force execution option in Termux:Tasker that skips the checks? I'd be interesting to see if there is a way to make Termux:Tasker aware of the mount, or to know why it isn't in the first place. 

### WHY?!

Mounting a folder to `~/.termux` is pretty weird. This procedure is only the minimum required for the bug to occur. What I actually did and lead me to this bug is that I encrypted the whole `/data/data/com.termux/files` using a LUKS encrypted ext4 image, for which I wrote a neat tutorial here: https://glow.li/posts/encrypt-termux-fs/

* Termux application version: 0.112
* Android OS version: 9
* Device model: FP3 (Fairphone)

**Comment by agnostic-apollo** [comment]
Hi,

Thanks for detailed report, quite refreshing to see one! Now lets get to business.

Firstly, your `script2` and `script3` commands are wrong. `script3` will override the log.

```
echo "echo 2 mounted > ~/log" >> ~/.termux/tasker/script2
echo "echo 3 mounted > ~/log" >> ~/.termux/tasker/script3
```

It should be following:

```
echo "echo 2 mounted > ~/log" > ~/.termux/tasker/script2
echo "echo 3 mounted >> ~/log" > ~/.termux/tasker/script3
```

Secondly, Termux:Tasker does test if a file is an executable regular file or not, but it also automatically [sets executable permission](https://github.com/termux/termux-tasker/blob/v0.5/app/src/main/java/com/termux/tasker/utils/FileUtils.java#L134) if script is under `~/.termux/tasker` when plugin action is [run](https://github.com/termux/termux-tasker/blob/v0.5/app/src/main/java/com/termux/tasker/FireReceiver.java#L84) but not when selecting script in [configuration screen](https://github.com/termux/termux-tasker/blob/v0.5/app/src/main/java/com/termux/tasker/EditConfigurationActivity.java#L316), note `setMissingPermissions` argument.


Anyways, as to detecting your problem, if you were on `v0.5` of Termux:Tasker, which I'm thinking you are not, the configuration screen should have shown errors like `Regular file not found at path` when entering `script3` as executable. Moreover, `%errmsg` would have returned same errors when running the plugin action. Check [Plugin Variables](https://github.com/termux/termux-tasker#plugin-variables). Also check [Template](https://github.com/termux/termux-tasker#templates) tasks on how to properly read them.

The real issue seems to be mount namespace. When you mount inside Termux shell, you are **not** mounting in global mount namespace, but that of the Termux app process. So Termux:Tasker app process does not see the mount point, and does not see the `script3`. Although, its weird that `script2` that is run is the mounted one because of `2 mounted` in `log` file instead of the unmounted one. Currently, not sure why, will need to investigate.

To mount in global namespace, if you are using my version of [sudo](https://github.com/agnostic-apollo/sudo), you can pass `--mount-master` to [`--su-run-options`](https://github.com/agnostic-apollo/sudo#Command-Options) option. Or mount directly with `su --mount-master -c mount --bind ~/test ~/.termux`

```
sudo --su-run-options='--mount-master' mount --bind ~/test ~/.termux   
sudo --su-run-options='--mount-master' mount | grep termux
sudo --su-run-options='--mount-master' umount ~/.termux~
```

You can confirm if you are in global namespace with the one liner by @mirfatif detailed [here](https://android.stackexchange.com/a/200449), including info on mount namespaces.

```
sudo su
[ "$(readlink /proc/self/ns/mnt)" = "$(readlink /proc/1/ns/mnt)" ] && echo 'In Global NS.' || echo 'Not in Global NS.'
exit

sudo --su-run-options='--mount-master' su
[ "$(readlink /proc/self/ns/mnt)" = "$(readlink /proc/1/ns/mnt)" ] && echo 'In Global NS.' || echo 'Not in Global NS.'

```

You can also change the mount namespace for all `su` commands run from MagiskManager `Mount Nampspace Mode` option, but its not advisable since that will create conflicts between apps, like for `rootfs` `ro` and `rw` remounts.

Note that, I have tested with an internal updated version of Termux:Tasker, which uses my [updated implementation of `FileUtils` being used in Termux app](https://github.com/termux/termux-app/blob/v0.112/termux-shared/src/main/java/com/termux/shared/file/FileUtils.java#L264) since [`v0.109`](https://github.com/termux/termux-app/releases/tag/v0.109) as per termux/termux-app@d4fc34ca2, so you might in fact be on `v0.5` but not get those errors mentioned, cause Java `File` APIs are [a complete mess](https://github.com/termux/termux-app/blob/v0.112/termux-shared/src/main/java/com/termux/shared/file/filesystem/FileTypes.java#L36).

**Comment by Neo-Oli** [comment]
Hi. Thanks for the quick and detailed answer. 

> Firstly, your script2 and script3 commands are wrong. script3 will override the log.

Ah, indeed. But this is only a mistake I made writing the issue. I tested it with the correct syntax. 

> Anyways, as to detecting your problem, if you were on v0.5 of Termux:Tasker, which I'm thinking you are not, the configuration screen should have shown errors like Regular file not found at path when entering script3 as executable

No, that's right. I am on v0.5 and I did see these errors. I just ignored them for this issue as I think it should work.

> The real issue seems to be mount namespace. When you mount inside Termux shell, you are not mounting in global mount namespace, but that of the Termux app process.

That actually explains a LOT. I've been having many different issues with mounting things with Termux for other apps, but I never figured out what exactly the reason for that was. 

> Although, its weird that script2 that is run is the mounted one because of 2 mounted in log file instead of the unmounted one. Currently, not sure why, will need to investigate.

Isn't that because the actual execution of the script is handed over to `com.termux.app.TermuxService`, which is in the correct mount namespace?
https://github.com/termux/termux-tasker/blob/552d592e841595e7d0a531dd1235c04948a42a57/app/src/main/java/com/termux/tasker/FireReceiver.java#L127-L128

> To mount in global namespace, if you are using my version of sudo, you can pass --mount-master to --su-run-options option. Or mount directly with su --mount-master -c mount --bind ~/test ~/.termux

I did not now about the different mount namespaces for android apps or the `--mount-master` flag. I was under the impression that when we switch to root with su, we've left the Termux environment completely. I will give this a try.

**Comment by agnostic-apollo** [comment]
> Hi. Thanks for the quick and detailed answer.

Welcome :)

> I tested it with the correct syntax.

Oh, okay.

> No, that's right. I am on v0.5 and I did see these errors. I just ignored them for this issue as I think it should work.

Well, at least should have mentioned that :p

> That actually explains a LOT. I've been having many different issues with mounting things with Termux for other apps, but I never figured out what exactly the reason for that was.

Yeah, that is a pretty common problem.

> Isn't that because the actual execution of the script is handed over to com.termux.app.TermuxService, which is in the correct mount namespace?

Yeah, you are right, that would be the reason. If you turn on isolated mount namespace mode in magisk, then it would return `2 normal`. (Will require unmount and app restart)

>I did not know about the different mount namespaces for android apps or the --mount-master flag. I was under the impression that when we switch to root with su, we've left the Termux environment completely. I will give this a try.

That probably was true in the SuperSU era (well, my era technically), usually people disabled namespace separation for xposed modules, etc, and mounts worked everywhere. The magisk era is more strict for security and safety reasons. You can check [this thread](https://www.reddit.com/r/tasker/comments/k3br7d) for more info.

Closing since not a Termux issue.
