### ISSUE TITLE
Commands that function when manually entered and not when executed in script

### ISSUE THREAD

**Issue by anndrewww** [termux/termux-tasker#5]
The following functions perfectly when manually entered into a Termux session:

`rsync -avz -e ssh XX@XXX.XXX.XXX:/home/XXX/Pictures/Snapshots /data/data/com.termux/files/home/downloads/Snapshots`

The same command has been copied into an executable (chmod +x) script, but when I attempt to execute via the command line (./SyncSnapshots) or via the Tasker plugin, the following is returned:

via command line: `bash: ./SyncSnapshots: Permission Denied`

via Tasker plugin: `exec("data/data.com.termux/files/home/.termux/tasker/SyncSnapshots"): Permission Denied`

**Comment by fornwall** [comment]
Sorry for the late reply here! I suspect that your `SyncSnapshots` file has a shebang like `#!/bin/sh` or similar which does not work under Termux, as Android does not have a `/bin` or `/usr` folder.

If it's a simple shell script, just remove the shebang. Otherwise run `termux-fix-shebang SyncSnapshots` to rewrite the shebang path before executing.
