### ISSUE TITLE
Cannot install: Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE]

### ISSUE THREAD

**Issue by jbrepogmailcom** [termux/termux-tasker#69]
**Problem description**

I have Android 6. I have got older version of termux (v 0.118.0+605dd6c) that still runs well and I downloaded termux:tasker v 0.4 for Android 5. The APK did not install in phone, so I tried ADB install and got error

**Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE]**

Is there any other method how to install?

**Steps to reproduce**

**Expected behavior**

**Additional information**

* Termux application version:
* Android OS version:
* Device model:

**Comment by jbrepogmailcom** [comment]
It may be because I have got older termux from somewhere and termux:tasker from F-Droid. Then users may not be compatible. Can you please provide termux:tasker v0.4 as compiled APK in releases? Thanks

**Comment by agnostic-apollo** [comment]
Github and F-Droid releases are not compatible.

https://github.com/termux/termux-tasker#installation

I have added support for android 5/6 with 10cc0475 and you can grab a build from https://github.com/termux/termux-tasker/actions/runs/2915176642

I got tasker licensing issues for android 5, so didn't test execution on it yet, only plugin config screen, but hopefully should work. I only tested execution on android 11. So tests from other users on Android 5/6 would be great to before a F-Droid release can be made.

I also suggest you read the README and release changelogs before asking other questions. There are lot of changes since last supported release.

https://github.com/termux/termux-tasker/releases

**Comment by jbrepogmailcom** [comment]
Thanks for your APK, but I am getting error INSTALL_FAILED_OLDER_SDK. I have API 23, Android 6. Jan

**Comment by agnostic-apollo** [comment]
The apk has following and should install fine on Android 6 and installs fine on Android `5`. There may be some conflict with already install app on your phone, uninstall it first.

```
    <uses-sdk
        android:minSdkVersion="21"
        android:targetSdkVersion="28" />
```
